name: Build MDITTER v1.5
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Manual Install Gradle 8.10
        # 彻底解决系统自带 8.1 不退出的问题
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.10-bin.zip
          unzip -q gradle-8.10-bin.zip
          echo "$(pwd)/gradle-8.10/bin" >> $GITHUB_PATH

      - name: Build with Gradle 8.10
        # 强制使用刚才安装的 8.10
        run: gradle build --no-daemon
